// Cleaned and deduplicated courtesy list
// Raw data processed: removed duplicates, validated emails
// Total unique recipients: 231

export interface CourtesyRecipient {
    name: string;
    email: string;
}

export const COURTESY_LIST: CourtesyRecipient[] = [
    { name: "Helmut Caroca", email: "hcaroca4@gmail.com" },
    { name: "Sigrid Tapia", email: "sigridromina98@gmail.com" },
    { name: "Bastian Ruiz", email: "81astian.contacto@gmail.com" },
    { name: "Hugo Novoa", email: "novoahugo11@gmail.com" },
    { name: "Amanda mella", email: "a.isatrujillo@gmail.com" },
    { name: "Gonzalo Perez", email: "gperezr22@gmail.com" },
    { name: "Caterina Ledda", email: "leddacaterinasb@gmail.com" },
    { name: "Ignacio Da Pena", email: "ignaciodp96skt@gmail.com" },
    { name: "benja ahumada", email: "ahumadasaav23@gmail.com" },
    { name: "Roberto Valenzuela", email: "robval.1721@gmail.com" },
    { name: "Leon marino", email: "leon123marino@gmail.com" },
    { name: "Alex Veas Munoz", email: "alexveasm08@gmail.com" },
    { name: "Martin Aguilera", email: "martinaguilerajara347@gmail.com" },
    { name: "Joaquin Sepulveda", email: "joaquinsepulveda823@gmail.com" },
    { name: "Monserrat Gonzalez", email: "monserratglagos@gmail.com" },
    { name: "Diego Cordova", email: "diegocordovalopez@gmail.com" },
    { name: "Sophia cisternas", email: "sophiacisternas8@gmail.com" },
    { name: "Lolita zepeda", email: "lolitazepedaaillon@gmail.com" },
    { name: "Javier Carriel", email: "javiercarriel7carriel@gmail.com" },
    { name: "Isaac brites", email: "isaacbrites1320@gmail.com" },
    { name: "Josefa Rivero", email: "riverojosefa10@gmail.com" },
    { name: "Camila castillo", email: "cxamilaaaaaa@gmail.com" },
    { name: "Monserrat Hernandez", email: "monserratcovarrubias90@gmail.com" },
    { name: "Tamara cadiz", email: "tamaracadiz06@gmail.com" },
    { name: "Javiera Orellana", email: "orellanajavierab@gmail.com" },
    { name: "Drago echague", email: "dragoechague@gmail.com" },
    { name: "Camila Perez", email: "camila.holi123@gmail.com" },
    { name: "Camila ulloa", email: "crosssx.dj@icloud.com" },
    { name: "Marcos Contreras Oliva", email: "marcosnath.videasta@gmail.com" },
    { name: "brian sebastian", email: "brian.severino176@gmail.com" },
    { name: "Maite Zaldua", email: "mpzaldua@gmail.com" },
    { name: "Lilen Vega", email: "anaiis.2397@gmail.com" },
    { name: "Felix hadad", email: "mundolocaciones@gmail.com" },
    { name: "Ignacio Fernandez", email: "ignaciofrm.0203@gmail.com" },
    { name: "Matilde soto", email: "matii.sotoo1234@gmail.com" },
    { name: "Javiera guaico", email: "javierahernandez408@gmail.com" },
    { name: "krissna", email: "olivareskrissna@gmail.com" },
    { name: "Gabriela Ortiz", email: "gpaz968@gmail.com" },
    { name: "Sebastian raffernau", email: "sebastian.e.diaz.diaz@gmail.com" },
    { name: "Manuel Valeria", email: "manuel.valeria.v@gmail.com" },
    { name: "Luisa Solar", email: "solarluisa014@gmail.com" },
    { name: "Catalina Riquelme", email: "catariquelmeg@gmail.com" },
    { name: "Barbara yanez", email: "bcyanezs@gmail.com" },
    { name: "Valentina Sepulveda", email: "sepulvedam.valentina@gmail.com" },
    { name: "Michel ruiz", email: "mmpelonn@gmail.com" },
    { name: "Vicente Arancibia", email: "vicentearancibiamoya03@gmail.com" },
    { name: "Daniela", email: "danielatobarriffo@gmail.com" },
    { name: "Constanza Aravena", email: "constanzarave.ca@gmail.com" },
    { name: "Branco Sanchez", email: "branco.sanchez.trini@gmail.com" },
    { name: "Tabhita teiguel", email: "tabhi.soto@gmail.com" },
    { name: "Paloma Miranda", email: "paloma.alexandra.07@gmail.com" },
    { name: "Javiera Toro", email: "javvieratoro@gmail.com" },
    { name: "Xiomara Mendoza", email: "mendozaxiomara478@gmail.com" },
    { name: "Gerald ahumada", email: "gerald.javier.diaz@gmail.com" },
    { name: "Trinidad Diaz", email: "trinidaddiaz548@gmail.com" },
    { name: "Dilan campillay", email: "campillaydilan@gmail.com" },
    { name: "Alejandro ahumada", email: "alejandroeledominio19@gmail.com" },
    { name: "Demys navia", email: "dem.navia@duocuc.cl" },
    { name: "Antonia Maldonado", email: "anto011126@gmail.com" },
    { name: "Ninoska Gajardo", email: "ninooskaa@gmail.com" },
    { name: "Fernanda Barriga", email: "fernandayalon@gmail.com" },
    { name: "Nicolas Arriagada", email: "arriagadanicolas15@gmail.com" },
    { name: "Ignaciocalizario", email: "ignaciocalizario1@gmail.com" },
    { name: "Cristopher Araya", email: "ccristopherr.ahp@gmail.com" },
    { name: "Krishna solis", email: "alexandrareyessolis@gmail.com" },
    { name: "Andres Barrera", email: "cowflowers@gmail.com" },
    { name: "Valentina Mendez", email: "vale0409.vm@gmail.com" },
    { name: "Francisca von Appen", email: "franciscavonappen@gmail.com" },
    { name: "Alondra Silva", email: "alondra.josefina.silva@gmail.com" },
    { name: "Antonia Dekovic", email: "antonia.dekovic.m@gmail.com" },
    { name: "vittorio ferrada zamora", email: "vferradazamora@gmail.com" },
    { name: "martina altamirano", email: "maltamiranoa@hotmail.es" },
    { name: "danfa aros", email: "danfa.aros@gmail.com" },
    { name: "Natalia vergara", email: "natalia.sofia.vergara2003@gmail.com" },
    { name: "Javiera Vergara", email: "huavivergara1128@gmail.com" },
    { name: "Rocio Silva", email: "rociosilvasagredo08@gmail.com" },
    { name: "Camila Molina", email: "camilamolina2411@gmail.com" },
    { name: "Kinverlin villaeca", email: "denissekymberly@gmail.com" },
    { name: "Matias Paredes", email: "matianpaher2001@gmail.com" },
    { name: "Katy romero", email: "katyromerohuaman8@gmail.com" },
    { name: "Ashly banda", email: "ashly17lia@gmail.com" },
    { name: "Kendall Rojas", email: "youngmoon23.business@gmail.com" },
    { name: "magdalena navarrete", email: "magdalenaalmarza6@gmail.com" },
    { name: "nerea lopez", email: "neere3a@gmail.com" },
    { name: "paulina daza", email: "paulinad894@gmail.com" },
    { name: "Alexandra Iturra", email: "ale.iturra25@gmail.com" },
    { name: "Thomas Molina", email: "thomasmolina0307@gmail.com" },
    { name: "Matias bruna", email: "matiibruna.69@gmail.com" },
    { name: "Vicente Munoz", email: "vicentecarlosmr@gmail.com" },
    { name: "Pablo Villarroel", email: "pemiliovf@gmail.com" },
    { name: "Kiara leiva", email: "leivakiara83@gmail.com" },
    { name: "Jonathan martinez", email: "jon.martinezc@duocuc.cl" },
    { name: "Cristian Yanez", email: "goryvoltio.musik@gmail.com" },
    { name: "Martina Gandarillas", email: "martinagandarillas0@gmail.com" },
    { name: "Rocio Aravena", email: "rocioaravenacornejo@gmail.com" },
    { name: "carlos quezada", email: "carlosquezadamillon@gmail.com" },
    { name: "anahi Casassus", email: "anahi.casassus.v@gmail.com" },
    { name: "Catrina leyton", email: "catrina.leyton02@gmail.com" },
    { name: "Vania Espinoza", email: "vaniaespinozan@gmail.com" },
    { name: "Vania Espinoza 2", email: "vanniariot1d@gmail.com" },
    { name: "Polonia Soto Libiot", email: "polonia.soto@gmail.com" },
    { name: "Juan Reyes", email: "juan.reyes.urquieta@gmail.com" },
    { name: "Javiera Mencia", email: "menciajaviera5@gmail.com" },
    { name: "Sophia Valenzuela", email: "sophia2004val@gmail.com" },
    { name: "Ivania Rodriguez", email: "ivaniaalexandra21@gmail.com" },
    { name: "Alexandra", email: "rosafuentes794@gmail.com" },
    { name: "Camila Carsolio", email: "camilacarsolio1@gmail.com" },
    { name: "Sebastian roa", email: "sroa765@gmail.com" },
    { name: "Luis Galvez", email: "f3l1p33w@gmail.com" },
    { name: "Betsabeth Echeverria", email: "betsabethecheverria2@gmail.com" },
    { name: "Felipe pinto", email: "f.pinto04@ufromail.cl" },
    { name: "Danko Gutierrez", email: "dankogutierrez93@gmail.com" },
    { name: "Edward Bruckner", email: "acc.ebcs@gmail.com" },
    { name: "Sebastian ross", email: "ross.arq@hotmail.com" },
    { name: "David gonzalez", email: "davii.gonzalez@duocuc.cl" },
    { name: "Luis Arellano", email: "alejandro.arellano92@gmail.com" },
    { name: "javiera contreras", email: "javieracontrerascaceres@gmail.com" },
    { name: "Larissa carvajal", email: "mateoeluneylarissa@gmail.com" },
    { name: "Che-en Fernando Wu Tang", email: "fernandowu33@gmail.com" },
    { name: "Miguel Vera", email: "mi.veradiaz7@gmail.com" },
    { name: "Darinka santander", email: "darinkasantander165@gmail.com" },
    { name: "Angelo Azua", email: "angeloazua9@gmail.com" },
    { name: "Camila olivares", email: "zcami157@gmail.com" },
    { name: "Nebula", email: "nebulaelbarbero@gmail.com" },
    { name: "Catalina Alarcon toro", email: "cata.alarcont@duocuc.cl" },
    { name: "Francisco lopez", email: "franciscolopezmorales17@gmail.com" },
    { name: "Francisco Gabriel Herrera", email: "franskbrdng@gmail.com" },
    { name: "Alejandro gonzalez", email: "ale.brante89gmail.com" },
    { name: "pia bahamondez", email: "piabelen152@gmail.com" },
    { name: "Fatima Figueroa", email: "fatimaandrea160@gmail.com" },
    { name: "Daniel tapia", email: "dt82903@gmail.com" },
    { name: "Estela panguilef", email: "panguilefnatalie35@gmail.com" },
    { name: "Renato Ortiz", email: "renatho313@gmail.com" },
    { name: "Mauricio yanez", email: "mauricioy072@gmail.com" },
    { name: "martina fuenzalida", email: "martina.fuenzalida@alumnos.uv.cl" },
    { name: "cristobal molina", email: "crstblmolina53@gmail.com" },
    { name: "cristobal molina 2", email: "molinacristobal004@gmail.com" },
    { name: "Miguel Alcaino Knabe", email: "knabe.tens.assistance@gmail.com" },
    { name: "Annais yepsen", email: "yepsenannais1@gmail.com" },
    { name: "Diego vergara", email: "diegovergarabat@gmail.com" },
    { name: "matias Bruna", email: "matiasbzapata@gmail.com" },
    { name: "Monserrat Aguilar", email: "aguilarmonserrat80@gmail.com" },
    { name: "Javier Orrego", email: "j.orrego2002@gmail.com" },
    { name: "Tatiana Cabrera", email: "tatianacabrera120103@gmail.com" },
    { name: "Genesis Alvarez", email: "genesis.monserrat.3@gmail.com" },
    { name: "Martin Rojas", email: "m.rojashorta17@gmail.com" },
    { name: "Cristobal romero", email: "cristobitom@gmail.com" },
    { name: "Fiorella toro", email: "fiorellatorogomez@gmail.com" },
    { name: "Martina contreras", email: "martinayuliet250@gmail.com" },
    { name: "Diego diaz", email: "di.dh9393@gmail.com" },
    { name: "Satcha Escobar", email: "satchaisidora2000@gmail.com" },
    { name: "Danilo Olea", email: "da.olea@duocuc.cl" },
    { name: "Renato Caceres", email: "renatotsq@gmail.com" },
    { name: "Alonso Silva", email: "alonsosilvamallea@gmail.com" },
    { name: "Nicole pais", email: "nicolepaisjofre@gmail.com" },
    { name: "Ignacia gonzalez", email: "ignaciag497@gmail.com" },
    { name: "Miguel Munoz", email: "mialmuse37@gmail.com" },
    { name: "Rodrigo Riffo Molina", email: "rjriffo1512@gmail.com" },
    { name: "Sebastian Casanova", email: "secadi13@gmail.com" },
    { name: "Marcelo zapata", email: "marcelozapapta@gmail.com" },
    { name: "Valentina Arrue", email: "valentina.arrue15@gmail.com" },
    { name: "Juan Gonzalez", email: "gonzalezvaldes.juan@gmail.com" },
    { name: "Cesar pangue", email: "cesarpangue@gmail.com" },
    { name: "Maria Gracia Lopez", email: "mariagraciapuc@gmail.com" },
    { name: "Maria Gracia", email: "mariagracia.lc04@gmail.com" },
    { name: "Ignacio Fernandez 2", email: "ignaciofrn.0203@gmail.com" },
    { name: "Leandro duran", email: "leandroxduran133@gmail.com" },
    { name: "Matilde Barahona", email: "matilditabarahona@gmail.com" },
    { name: "Krishna Aguilera", email: "krishnaaguilera884@gmail.com" },
    { name: "Denys fierro", email: "denysfierro0tdm@gmail.com" },
    { name: "Renata cardenas", email: "rnta.sagredo@gmail.com" },
    { name: "Jaime Castro", email: "castrojaime@gmail.com" },
    { name: "Javiera Mora", email: "javiera.mora.r@mail.pucv.cl" },
    { name: "Catalina marin", email: "catahm8@gmail.com" },
    { name: "claudio espinoza", email: "claudio.e13@gmail.com" },
    { name: "vania huerta", email: "vaniahuerta69@gmail.com" },
    { name: "Fabian Maulme Rojas", email: "fabianmaulmerojas@gmail.com" },
    { name: "Ignacio roco", email: "ignacioroco23@gmail.com" },
    { name: "Ambar Nunez", email: "ambarn95@gmail.com" },
    { name: "Cris Goldberg", email: "crisandresgoldberg@gmail.com" },
    { name: "Tomas Toledo", email: "tomastoledoescobar1313@gmail.com" },
    { name: "Adrian Salas", email: "adriansalas1903@gmail.com" },
    { name: "Nicolas santander", email: "nicof266@gmail.com" },
    { name: "Juan Antonio munoz", email: "jamuval2016@gmail.com" },
    { name: "Elias Oyarzun", email: "eliasoyarzun7@gmail.com" },
    { name: "Victoria Larrieu", email: "larrieuvictoria2401@gmail.com" },
    { name: "catalina garrido", email: "garridocatalina91@gmail.com" },
    { name: "Paz Ramirez", email: "pazramirezdelavega@gmail.com" },
    { name: "Ayling Avendano", email: "aylingtamaraagomez@gmail.com" },
    { name: "Jose Escribano", email: "joseescribano205@gmail.com" },
    { name: "Aileen lagunas", email: "aileen_lagunas@outlook.com" },
    { name: "Millaray barros", email: "millabafu@gmail.com" },
    { name: "Fabian nunez moyla", email: "nunezmoylafabianerick@gmail.com" },
    { name: "Angiel Guerra", email: "kaliscape@gmail.com" },
    { name: "Josefina rojas", email: "jeimmy.antonia@hotmail.com" },
    { name: "Alvaro Iturra", email: "alvaroiturraquiroz@gmail.com" },
    { name: "Martina arellano", email: "arellanolopez2005@gmail.com" },
    { name: "Alexander Cristensen", email: "alexandercristensenolmedo13@gmail.com" },
    { name: "cristian garrido", email: "cristianalexis.gc@gmail.com" },
    { name: "Pedro Nunez", email: "pedretg43@gmail.com" },
    { name: "Claudio Ojeda", email: "claudio.ojeda966@gmail.com" },
    { name: "Pedro Nunez 2", email: "devenga3@gmail.com" },
    { name: "Sebastian Alarcon", email: "salarconmartin@gmail.com" },
    { name: "Carlos Tobar", email: "xikotobar@gmail.com" },
    { name: "Constance Perez", email: "constancepj20@gmail.com" },
    { name: "Matias Monsalvez", email: "matimonza12@gmail.com" },
    { name: "Ricardo vera", email: "martin.veraluna@icloud.com" },
    { name: "Emilio cordero", email: "emilianozsw@gmail.com" },
    { name: "Esperanza cofre", email: "espe.cofre@gmail.com" },
    { name: "Tomas Lavergne", email: "tomaslavergne556@gmail.com" },
    { name: "Ignacio Garay", email: "habibjiraz@gmail.com" },
    { name: "Marcelo Silva", email: "marhugo20001@gmail.com" },
    { name: "ahilin maldonado", email: "ahilin.maldonado@gmail.com" },
    { name: "Claudia", email: "claudia.herrera.carvajal@gmail.com" },
    { name: "isidora cordova", email: "isidoracordova543@gmail.com" },
    { name: "Benjamin Ruiz", email: "bruizyanez2004@gmail.com" },
    { name: "Valeria Dolezol", email: "valeria.dolezal@hotmail.com" },
    { name: "fernanda inostroza", email: "fe.inostroza88@gmail.com" },
    { name: "Gregory Bracho", email: "brachogregory2@gmail.com" },
    { name: "Bastian Ruiz 2", email: "8astian.contacto@gmail.com" },
    { name: "Brayan Vasquez", email: "brayan.13.azul@gmail.com" },
    { name: "Hernan Aguirre", email: "he.aguirre@live.com" },
    { name: "Dafne Suarez", email: "dafnesuarez5@gmail.com" },
    { name: "Rafaella Sanginetto", email: "sanginettogabrielle@gmail.com" },
    { name: "tiaret friz", email: "dabrathe@gmail.com" },
    { name: "Antonella Crovo", email: "antonellacrovo2003@gmail.com" },
    { name: "yislein osorio", email: "yislein.osorio2002@gmail.com" },
    { name: "gabriel curilen", email: "gabo.curilen15@gmail.com" },
    { name: "Pablo monsalves", email: "pabloenriquemonsalvesvidal@gmail.com" },
    { name: "Nikolas Sanchez", email: "nik.sanchez@duocuc.cl" },
    { name: "Lucia Gomez", email: "lucia.milen99@gmail.com" },
    { name: "Sebastian Apablaza", email: "apa.seba22@gmail.com" },
    { name: "Matias Ruiz", email: "matiasruizlobos2001@gmail.com" },
    { name: "Victor Caneo", email: "torviktt@gmail.com" },
    { name: "Josu Rodriguez", email: "josuxcx@gmail.com" },
    { name: "Antonia Aravena", email: "anto.aravena002@gmail.com" },
    { name: "Maximiliano Quiroz", email: "maxiquiroz88@gmail.com" },
    { name: "Fabian Basaure", email: "fybasaure@gmail.com" },
    { name: "Constanza Cartagena", email: "cartagenaconstanza5@gmail.com" },
    { name: "Francisco Navarrete", email: "navarretefrancisco096@gmail.com" },
    { name: "Michelle hidalgo", email: "hidalgomichelle66@gmail.com" },
    { name: "Natalia Mena", email: "natalia.4am@gmail.com" },
    { name: "Eugene Tine", email: "eugenetine2000@yahoo.fr" },
    { name: "Valentina Orellana", email: "valeorellana45@gmail.com" },
    { name: "Bastian Leyton", email: "bastianleyton0.8@gmail.com" },
    { name: "Javier Martinez", email: "martinez.javier@outlook.es" },
    { name: "Sofia arevalo", email: "sofia.arevalor@gmail.com" },
    { name: "Kayleigh Hidalgo", email: "kayhidalgo30@gmail.com" },
    { name: "Constanza mora", email: "constanzajt.moracampos@gmail.com" },
    { name: "Gerson Aguilera", email: "grsnglra@gmail.com" },
    { name: "Leftraro Canepa", email: "leftraro.canepa@gmail.com" },
    { name: "Fernanda Silva", email: "fernandamily123@gmail.com" },
    { name: "Gabriel Bugueno", email: "gabriiel.natsux@gmail.com" },
    { name: "Pedro Galdames", email: "he.is.sketch@gmail.com" },
    { name: "Cristopher Munoz", email: "danimillaguinca.3010@gmail.com" },
    { name: "Cristopher Munoz 2", email: "cristopher.munoz2907@gmail.com" },
    { name: "Daniela Nunez", email: "nunezdanielaandrea@gmail.com" },
    { name: "Diego Hernandez", email: "diegoconcierre@gmail.com" },
    { name: "Carlos Perez", email: "zushatter@gmail.com" },
    { name: "Belen caraccioli", email: "belenpozacohen@gmail.com" },
    { name: "Andrea Figueroa", email: "andrea.figueroa.a01@gmail.com" },
    { name: "Milagros Mendoza", email: "dinarvichmendoza@gmail.com" },
    { name: "Alejandra", email: "soluciones.avaltay@gmail.com" },
    { name: "Julio De la Vega", email: "j.delavegamena@gmail.com" },
    { name: "Cristal gomez", email: "vidal.kathlenandrea@cftpucv.cl" },
    { name: "Kathleen Avalos", email: "kathleen.avalos.vidal@gmail.com" },
    { name: "Sofia thomson", email: "sofia.thomson@mail.udp.cl" },
    { name: "Andres abello", email: "andres.abello.v@gmail.com" },
    { name: "Alvaro Ramirez", email: "alvaro.ramirez1810@gmail.com" },
    { name: "Romina Merida", email: "meridayaksic@gmail.com" },
    { name: "Juan Moreno", email: "juanmoreno_uv@yahoo.com" },
    { name: "Cinthya Aguilar", email: "ci.aguilar24@gmail.com" },
    { name: "Giuliana Villegas", email: "giuliana.villegas10@gmail.com" },
    { name: "Carol Villegas", email: "villegassaavedracarol@gmail.com" },
    { name: "jhonathan castillo", email: "crupics@gmail.com" },
    { name: "Luis flores", email: "flores.lavin.luis@gmail.com" },
    { name: "Agustin Nunez", email: "agustinalonso.nunez@gmail.com" },
    { name: "Maite Ogalde", email: "maiteogalde.14@gmail.com" },
    { name: "Ulises", email: "ulisesdiaz2005@gmail.com" },
    { name: "Romina Donoso", email: "rominadonoso05@gmail.com" },
    { name: "Alonso Gonzalez", email: "agonzalez15112004@gmqil.com" },
    { name: "Melany Barraza", email: "melany07barraza@gmail.com" },
    { name: "kevin fuentealba", email: "kevin_bmx_10@hotmail.com" },
    { name: "Alonso Chacon", email: "rock.alonso.10.1@gmail.com" },
    { name: "matias sereno", email: "matsereno@gmail.com" },
    { name: "Mariana Cavallar", email: "maricavallardelgado@gmail.com" },
    { name: "Carla Huichaman", email: "carlihuicha@gmail.com" },
    { name: "Paula Hernandez", email: "paulahernandeztoro@gmail.com" },
    { name: "Esteban Fernandez", email: "efernandez.leo@gmail.com" },
    { name: "Aldo Opazo", email: "aldo.opazo.montecinos@gmail.com" },
    { name: "Eduardo Hauyon", email: "eduardohauyon1@gmail.com" },
    { name: "Moira Wiegand", email: "moirawiegandherrera@icloud.com" },
    { name: "Rayen Ulloa", email: "rayen.u.nail@gmail.com" },
    { name: "bastian rojas", email: "bastoxlml@gmail.com" },
    { name: "Jeffersson Flores", email: "jefferssonflores14@gmail.com" },
    { name: "Francisco Maldonado", email: "franciscolizana898@gmail.com" },
    { name: "Marco silva", email: "marcosilvacayupe@gmail.com" },
    { name: "Rodrigo Yanez", email: "marianoej2@gmail.com" },
    { name: "Katrina flores", email: "katt.flrss@gmail.com" },
    { name: "Javier vicencio", email: "j.vicenciosoto@gmail.com" },
    { name: "Nicolas Rivera", email: "nico.riverahidalgo@gmail.com" },
    { name: "Catalina hormazabal", email: "catita.hormazabal13@gmail.com" },
    { name: "Maico Guerra", email: "maicoguerranunez@gmail.com" },
    { name: "Paloma Alvarez", email: "paloma.alvarez.c@gmail.com" },
    { name: "Macarena suazo", email: "mcrnsuazo@gmail.com" },
    { name: "Diego Camilo", email: "diegocamilo@icloud.com" },
    { name: "Pablo ramos", email: "pabloramosmonjes@gmail.com" },
    { name: "kriss araya", email: "kriss.araya33@gmail.com" },
    { name: "Osvaldo olivares", email: "oolivaresriquelme@gmail.com" },
    { name: "Lucas cabrera", email: "wlsfask@gmail.com" },
    { name: "Sol feliu", email: "solfeliu4@gmail.com" },
    { name: "Ismael Bracho", email: "ismaelj0793@gmail.com" },
    { name: "Camila figueroa", email: "camila.gatunia@gmail.com" },
    { name: "Caroline Diaz", email: "carolinediaz.m@gmail.com" },
    { name: "Sebastian Barrientos", email: "nicobarrientos45@gmail.com" },
    { name: "Vicente Camilo", email: "vicentecamilo.m@gmail.com" },
    { name: "Constanza Donoso", email: "cony1902donoso@gmail.com" },
    { name: "Nicolas avila", email: "nico.avila.rodriguez@gmail.com" },
    { name: "Maria Fernanda Heredia", email: "ferherediae@gmail.com" },
    { name: "Nino Gomez", email: "nino.gomez@gmail.com" },
    { name: "Leon arevalo", email: "teamoriver24@hotmail.com" },
    { name: "Francisco Yanez", email: "bravia.francisco@gmail.com" },
    { name: "Valentina Almeida", email: "retamalesvalentina07@gmail.com" },
    { name: "Scarlett urrutia", email: "nicolurrutiag@gmail.com" },
    { name: "Katherinna gonzalez", email: "kittygonzalezarmy@gmail.com" },
    { name: "Roberto Saavedra", email: "rob.saavedra@hotmail.com" },
    { name: "Francisco munoz", email: "franciscomunoz1004@gmail.com" },
    { name: "Matias castaneda", email: "mjcalvarez08@gmail.com" },
    { name: "Catherine Esquivel", email: "catherinesquivel@gmail.com" },
    { name: "Angiee luna", email: "angelica.m.luna.g@gmail.com" },
    { name: "Angelica luna", email: "luna.oks2016@gmail.com" },
    { name: "Martin Teke", email: "martinteke555@gmail.com" },
    { name: "Fernando Vasquez", email: "fernando.contreras.vasquez@gmail.com" },
    { name: "Tomas Tello", email: "ttello46@gmail.com" },
    { name: "Sebastian medina", email: "girouudseba@gmail.com" },
    { name: "Bayron Perez", email: "bayruto@gmail.com" },
    { name: "Marianna Tilleria", email: "tilleriamarianna14@gmail.com" },
    { name: "Paulina Soler", email: "ykun1529@gmail.com" },
    { name: "Marcela Kohnenkamp", email: "marcela.koh@gmail.com" },
    { name: "Daniel lopez", email: "daniel.l.carroza@gmail.com" },
    { name: "Camilo Toro", email: "ctoro.urquiza@gmail.com" },
    { name: "Benjamin vivar", email: "marcellinoparra27@gmail.com" },
    { name: "Camila Berrios", email: "kamila-monze@hotmail.com" },
    { name: "Gabriela Aguilera", email: "gaba.v.a.h09@gmail.com" },
    { name: "Gerson ortega", email: "ortegagerson86@gmail.com" },
    { name: "Jarold Farias", email: "jarold.fariasf@estudiantes.arcos.cl" },
    { name: "Nallely Fernandez", email: "nallelyfernandez1234@gmail.com" },
    { name: "Valentina aguilar", email: "valeeaguilar01@gmail.com" },
    { name: "jose illanes", email: "illanesjoseignacio@gmail.com" },
    { name: "Allyson patino", email: "allysonmartinezpati0508@gmail.com" },
    { name: "Catalina Estay", email: "catalinaev2005@gmail.com" },
    { name: "Camilo campos", email: "camilo.camposog@gmail.com" },
    { name: "Paulina Cuevas", email: "cuevasfernandezp@gmail.com" },
    { name: "Vicente zlatar", email: "vicentezlatar27@gmail.com" },
    { name: "Carlos Kupfer", email: "kupfercarlos004@gmail.com" },
    { name: "Sofia bustos", email: "shinita.sofita.15@gmail.com" },
    { name: "Paula Castillo", email: "paula.castillo.loyola18@gmail.com" },
];
